### ISSUE TITLE
Team Contacts - improvements

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/adventisthub-support#103]
Add exporting of contacts to csv
Add table view of cards
Create marketing lists based on selection of contacts

**Comment by lasedgman** [comment]
Suggesting creating individual issues for these points (and closing this one):

- Table view of cards to be included in _Dash_?
-  Concept of lists/groups have been added as another issue
- Is there a current need for exporting CSV of contacts? IF there is, let's create a new issue for this. If not, leave this feature out until it is requested by multiple users and teams.
