### ISSUE TITLE
Unsubscribe from Alert emails

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/adventisthub-support#108]
Create a subscription for Alert emails. This would be auto subscribed for new contacts.

A link should appear in emails to unsubscribe

**Comment by cristiansc** [comment]
Would the unsubscribe link turn off alert emails for all notifications? Or just for that particular contact?

**Comment by danlewis** [comment]
Initially it would turn if off for all notifications. 
In the future we may allow unsubscribing from types of alerts e.g. unsubscribe from happy birthday alerts, or transfer alerts, etc..

**Comment by danlewis** [comment]
Added and live
