### ISSUE TITLE
Support Alerts - on/off

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/adventisthub-support#109]
A flag should exist to turn on and off support alerts for individual contacts.

E.g. A young child in the church who is not a member should not have support alerts generated if their not followed up

**Comment by cristiansc** [comment]
agreed - default is for alerts to be enabled for non-members - but can be switched off as needed.

**Comment by danlewis** [comment]
on second thought - support alerts are currently only generated when activity has not been followed up. This should be true regardless of the person. 

I think i originally mixed the idea of this issue with the concept of a alert been generated for contact who is not been regularly followed up. This would be a different feature that currently doesn't exist.
