### ISSUE TITLE
Complete/uncomplete items

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#110]
At the moment, when adding a new activity via the 'search' bar, it creates a 'completed' todo/activity.

When importing a bulk list of contacts, it also creates a 'completed' todo.

Is there a way to turn completion on/off from within the edit window for an activity rather than having the option of creating 'todo' or 'competed' activity? i.e. only one 'add activity' option - single click - within the 'new activity' window you can select (checkbox) wether it is completed or tbc.

Also is there a way to have a check box next to each activity on the 'activity' tab that simply allows activities to be completed or uncompleted?

**Comment by danlewis** [comment]
1. The search bar add activity already creates a todo activity.
2. bulk importing contacts only has the a decisions field. A contact completing a decision card is in itself a completed activity, however the decision should generate additional todo activities based on the decisions that were made. This would be part of a seperate feature specifically designed around how decisions are made and recorded at events.
3. not at present
4. no - completing an activity includes fields for when the activity was completed and and additional notes to what happened and hence to complete an activity a modal box is opened up. We have however added the option to Uncomplete an activity for the next release.
