### ISSUE TITLE
CSV template download Link for bulk adds not working

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#112]
Getting the following error message:

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by cristiansc** [comment]
Can we also please add a column for membership status? i.e. member/non-member.

This is so churches can import bulk membership lists directly

**Comment by lsamon** [comment]
This issue has been resolved.
