### ISSUE TITLE
+ Gender column to CSV file

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#116]

**Comment by lasedgman** [comment]
@danlewis, Just looking at the Bulk upload page vs the downloadable CSV template and it is already listed on the page but not on the template. 

Does a user need to manually add the 'Gender' column, or is the CSV template an older version?

**Template**
![screen shot 2017-09-26 at 12 31 24 pm](https://user-images.githubusercontent.com/8165750/30839988-2b6231c0-a2b8-11e7-9a21-161a90ae1e03.png)

**Page**
![screen shot 2017-09-26 at 12 31 33 pm](https://user-images.githubusercontent.com/8165750/30839987-2b602344-a2b8-11e7-94b8-d2dccc85c88a.png)

**Comment by lasedgman** [comment]
fixed

**Comment by cristiansc** [comment]
Can we provide an example of the data needed to validate the gender column? i.e. is it 'male' and 'female' or 'm, 'f', etc
