### ISSUE TITLE
What if we used 'membership' header instead of 'status'?

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#118]
And also, when filtering by 'status'/membership in team contacts, can we have 3 categories instead of 2?
currently - member / non-member

requested - user / member / non-member

**Comment by danlewis** [comment]
User isn't a type of status but rather whether you have an account. So all contacts whether there member or non_member can have an account
A contact also has a account_status which has the fields no_account, pending, active, disabled. As the state of accounts is already available in Team Dashboard > Members I don't think it's necessary to duplicate it in team contacts.
