### ISSUE TITLE
No 'review' option for transfer between teams

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#119]
Jenny White (NA HQ user and NAC Departmental user) did the following:

1. Bulk upload csv file (1 contact) in NA HQ
2. Assigned contact to NAC Departmental Team
3. The contact was auto accepted - there was no invitation to review/accept/decline - it auto accepted it.

Is this because Jenny was the user doing both? Is it possible to have the review step regardless of who transfers contacts across?

**Comment by danlewis** [comment]
When an HQ transfers a contact to team it is auto-approved. When a Hub team transfers a contact to another Hub it must be review.

We will soon be removing Contact management from HQ and so if this is an issue it won't be soon :)
