### ISSUE TITLE
Event time/date bug

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#122]
From User

3) When I start an event, I can set the time but for "end time" it only shows the calendar and not the clock and yet provides a red error message saying "end time must be before start time" but I can't input a end time because it doesn't show.

**Comment by cristiansc** [comment]
bump

**Comment by lasedgman** [comment]
@danlewis to followup on this

**Comment by cristiansc** [comment]
bump - feedback from users at ministers meetings again today

"hi Cristian

When I try to add an event on Adhub the "End Time" has a calendar but no clock so can't really add an end time which leads to error in trying to save the event"

**Comment by danlewis** [comment]
Fix is included in the next major release.
