### ISSUE TITLE
myadventist login without existing social media account

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#13]
Some local members who are not employed staff may not have a Google, FB, MS or yahoo account - how can they log-in or create a myadventist account?

**Comment by amnwebmaster** [comment]
At myadventist.org.au in the top right corner there is a "New Profile" button. On that page (https://myadventist.org.au/profile/new/ssportal/1) is a ways to create an account and in small letters that you can optionally create a myAdventist profile with a valid email and provides a link.

SPD could definitely make that a lot easier too see. You may find its better to provide a link disciples site directly to the New Account page (https://myadventist.org.au/profile/create/ssportal/1)

**Comment by cristiansc** [comment]
Thanks Dan,

However this still only allows me to create an account with an existing provider such as google, FB, Microsoft, yahoo or staff - it doesn’t give me an option (or at least one that I can see) to use my own email/password not related to another 3rd party.

**Comment by amnwebmaster** [comment]
The New Profile page has a link at the very bottom in gray text which links to https://myadventist.org.au/profile/create/ssportal/1
This page asks for a name and email address and then sends the user an activation email to set a password:
Email Text:
To set your 'MyAdventist' password click on the link below.

Set My Password (link)

Thanks

**Comment by cristiansc** [comment]
Gerat - thanks Dan - if you hadn't pointed out the greyed text I wouldn't have noticed it - I just assumed it was a disclaimer - is this something you are able to ask them to improve?

**Comment by amnwebmaster** [comment]
I've cc'd you in on an email to service desk request the link to be more obvious.. We'll see what happens.

**Comment by cristiansc** [comment]
Great :)

Thanks


________________________________

This message may contain both confidential and privileged information intended only for the addressee named above. If you are not the intended recipient you are hereby notified that any dissemination, distribution or reproduction of this message is prohibited. If you have received this message in error please notify the sender immediately, then destroy the original message. Any views expressed in this message are those of the individual sender.
