### ISSUE TITLE
no auto select for mail/maps app on iOS

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#130]
Not sure on Android, but when I click on 'mail' or 'directions' it takes me to the default iOS apps "apple mail" and "apple maps" - neither of which I use.

Is there a way to allow me to choose which mail/maps apps I want to use?

**Comment by danlewis** [comment]
iOS does not support the feature.

You can try reading this https://www.imobie.com/support/how-to-make-google-maps-default-on-iphone.htm for a version that worked for older iOS versions. In the comments they mention a hack way that might work.

Either way best bet is to make a feature request for apple

**Comment by brettdonald** [comment]
Apple doesn't provide the ability to choose a default browser, mail client or mapping client. However, you can delete the Apple Maps app if you don't use it. Opinion seems divided on whether this will allow Google Maps to "take over" as the default mapping app, but it might be worth a try.

Google Maps [provides ways](https://developers.google.com/maps/documentation/ios-sdk/urlscheme) for app developers to open Google Maps. So we could theoretically build a switch into the app which would allow users to choose between Apple Maps and Google Maps. This would be fairly easy to do, perhaps a day's worth of work.

Your favourite email app may provide similar hooks for developers, and it may not, but it would have to be a pretty popular app in order for us to consider integrating with it specifically. An additional complicating factor for email is that we are using a third-party library to make it easy to initiate phone calls, emails and texts in a cross-platform-friendly way, which means supporting alternative mail apps will be more work for us than supporting alternative mapping apps.

**Comment by cristiansc** [comment]
no worries - not a major issue/feature - just if it was easy/simple to do - which it seems it is not :)
