### ISSUE TITLE
'deceased'  status - how relevant/necessary is this?

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#131]
I'm wondering if it is worth removing 'deceased' altogether. When a person passes away, it is unlikely their details will be needed again.

Perhaps have an 'archive' option like we do for 'deleting' contacts? or alternatively users can just delete the contact

**Comment by lasedgman** [comment]
The **Archived** status could also be used where a contact was shared but then ends up only interacting with a 1 of those teams - the other team could then archive the contact eg. contact moves away etc.

Would archiving also require a **view** to see all **Archived** contacts (Possibly under the team contacts nav item)?

**Comment by cristiansc** [comment]
Any update on this?
Perhaps for status have
* Member
* Non-Member
* Inactive

When "Inactive" is selected, accountability process turns off - at the moment, I'm not sure what process there is to turn accountability process?

**Comment by danlewis** [comment]
changed to inactive
