### ISSUE TITLE
Mobile App can assign contacts to 'non-member' contacts

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#133]
When clicking 'assigned to' on a contact in mobile app, it shows a list of all 'team' contacts to assign contact to, including non-members/users - it should really only be showing 'users' as potential assignors.

**Comment by danlewis** [comment]
This is correct as happens in the web app.
A contact does not need to be a user to be assigned another contact. For example, a pastor should still be able to assign contacts to an elder in the church even if the elder is not a user of AdHub. This way the pastor can still keep track of who looks after who without having to keep a seperate list somewhere else.

**Comment by cristiansc** [comment]
the web app doesn't show 'non-members' as possible assignors - at least not in the version I checked this morning.
For example - in team Sample - on the app, I can assign Lizzy Mitcahm (non-member) to Mike Cheng (non-member) - however in the web app, I can't assign Lizzy to Mike.

Shouldn't be able to assign contacts to 'non-members'

**Comment by cristiansc** [comment]
seems to be fixed - at least not showing 'non-members' in my 'assignor' list on the mobile app
