### ISSUE TITLE
Comment box for all transfers in/out/decline etc

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#136]
When transferring a contact out, can we please have a comment/details box available. Same for 'accepting' a contact

**Comment by danlewis** [comment]
transferring out is been replaced with sharing contacts in the next release. Sharing contact allows for a reason to be written when sharing. When accepting/declining  feedback can also be given

**Comment by cristiansc** [comment]
great :)

**Comment by cristiansc** [comment]
done in this release
