### ISSUE TITLE
Blue welcome splash screen

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#139]
Can we remove the blue 'intro' splash screen when people sign in to a new account? On Tuesday I saw at least two pastors who have had accounts previously activated with the seals screen still there - they didn't realise they could close it. And I'm not sure if it adds any value

**Comment by lasedgman** [comment]
Agree, we should remove this - Would be great at a later stage to have an on-boarding experience on first time log in like a tour, guide, walkthrough, or features highlight.

**Comment by brettdonald** [comment]
I haven't seen this for ages, so not sure what information it contains, but perhaps we could adjust it so that it only shows on first login, and never again?

**Comment by cristiansc** [comment]
removed
