### ISSUE TITLE
Contact view shows all contacts, not just for selected teams

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#14]
Can we have a filter option where you can view contacts by team rather than showing all contacts? e.g. I am manager/leader/member of 5 teams - when I click on my contacts, I can see contacts from all teams without an option to filter by team.

**Comment by cristiansc** [comment]
And by extension, is there a way to in a contacts Summary view what team/s they are part of?

**Comment by amnwebmaster** [comment]
This is an interesting question I have pondered about myself.
Really every single navigation item should only show objects for the current team your view. So for example contacts should only show contacts for the Hub team you're in. Events should only show events for the Hub team your in, etc.

For all other areas other than Contacts this is the case. Currently it's written such that Contacts  shows all contacts regardless of which team you've selected. This can be very helpful if your country pastor with 5 churches as you wouldn't need to think - Mary Jane.. which team did I add her too.. and then switch to that team.
Really though, thats how it should work - complete separation of data.

The number of members who actually do belong to multiple Hubs would be small however so maybe this isn't a bad thing..

I don't think there should be a list of teams in the contacts filter as this would be more confusing. For example if you were on Hub Team A and then if you went to view Contacts and saw Hub Team B contacts (forgetting you had applied the filter) you may start doing things you didn't intend too.

**Comment by cristiansc** [comment]
Is it possible to add a 'team' column in the contacts view?

**Comment by brettdonald** [comment]
Completed
