### ISSUE TITLE
Importing contact list - Validation error on import

### ISSUE THREAD

**Issue by lasedgman** [adventistmedia/adventisthub-support#142]
Had success with importing a couple of contacts, failed on this one - Contact only has a phone number. 

![group_1](https://user-images.githubusercontent.com/8165750/32995418-cb877e6e-cdc7-11e7-90e8-91af3030da7f.png)

**Comment by brettdonald** [comment]
I created a contact with First Name = "Test 22", Last Name = "Contact", Phone Number = "0413 752 403", but it imported fine for me. I see you haven't included the name of your contact. Is there anything special about your contact's name -- hyphens, diacritics, etc? Could you try to isolate the problem further by:

- creating a new contact in your phone with a different name but the same phone number, and attempting to import
- creating a new contact in your phone with the same name but a different phone number, and attempting to import

Thanks, Brett

**Comment by lasedgman** [comment]
New contact - Different name but the same phone number - Validation error
![img_6677](https://user-images.githubusercontent.com/8165750/33041817-bdf5310c-ce93-11e7-9d4b-ce844f086db5.PNG)

**Comment by lasedgman** [comment]
New contact - Same name, different same phone number - Validation error
![img_6678 1](https://user-images.githubusercontent.com/8165750/33042255-3cd6361e-ce95-11e7-92f8-005bab2fb984.PNG)
