### ISSUE TITLE
Notifications not displaying

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#15]
I created a new contact in team Bunbury and assigned to Mike Smith at the initial new contact creation stage - however no notification displayed for Mike Smith that he was receiving a new contact

**Comment by cristiansc** [comment]
I can see that the notifications work when re-assigning existing contacts - but it doesn't seem to work when assigning a new contact at creation

**Comment by amnwebmaster** [comment]
This has been fixed for the next release.

**Comment by amnwebmaster** [comment]
Live. Please reopen if still an issue.
