### ISSUE TITLE
Added existing 'user' to new team - but not auto-filling

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#153]
Added yulitjokro@adventist.org.au to team Sample.

typing in her email in the 'email' field for new user did not auto-complete - I had to add all the details manually

**Comment by danlewis** [comment]
yes autocomplete only searches contacts you already have in your team (e.g. they maybe contacts who who aren't users).
We don't allow autocomplete to search all users in AdHub as that would present a security issue - where typing a couple of letters shows you the name and private email address of any one in AdHub.
