### ISSUE TITLE
Mentorships filter not updating

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#17]
When viewing teams in the mentorship tab, the filter text does not correlate to the selected view. e.g. If I select the team Western Australia, it shows me the teams I am mentoring in WA however the filter tag still stays stuck on Antaratica - which is the first available filter tag

**Comment by amnwebmaster** [comment]
I believe this was a caching issue. A fix is ready for the next release

**Comment by amnwebmaster** [comment]
Live. Please reopen if still an issue.
