### ISSUE TITLE
Difference between 'users' and 'members' tab

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#23]
what's the main significant difference between 'users' and 'members' - is it possible to roll these into one single tab to avoid confusion?

**Comment by amnwebmaster** [comment]
I'm guessing your referring to inside the HQ?

In the navigation menu are two sections (HUBS and HQ)
All nav items under HUBS refers to Hub teams.. e.g. you could read them as Hub Brands, Hub Contacts, Hub Users.
Hence Users there is referring to all users from all Hub teams that belong to the HQ.

The HQ section of the nav have nav items which are directly related to your HQ team. Hence Members is the list of user memberships for your HQ team and is where you set their roles.

The two sections could not be combined.

**Comment by cristiansc** [comment]
Got it - I guess because I was using the same set of test users, both lists looked identical and I didn't notice the difference - thanks for the clarification.
