### ISSUE TITLE
Adding instance to "special event" not working

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#24]
In team Bunbury, under HQ Western Australia, I created a special recurring event series called "Sabbath Worship Service". When I click on the 'add event' button under this special recurring event, it jus takes me back to the main "add event' page like as if I had clicked the 'events' tab in the left nav bar.

**Comment by amnwebmaster** [comment]
Fixed for next release

**Comment by amnwebmaster** [comment]
Live. Please reopen if still an issue.
