### ISSUE TITLE
Froze search/top menu bar

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#25]
Not urgent, and not sure if possible, but especially when dealing with large lists (e.g. teams or contacts), is it possible to get the search bar and menu items underneath it (e.g. add team/contact) to stay frozen/sticky to the top of the window?

**Comment by lasedgman** [comment]
@cristiansc are you referring to this?
![screen shot 2017-09-26 at 11 31 29 am](https://user-images.githubusercontent.com/8165750/30838339-4b80cc14-a2ae-11e7-8c60-04454de8d801.png)

**Comment by cristiansc** [comment]
yep - when you scroll down the page, the search bar disappears - wondering if it is possible to freeze the search bar frame so it always displays, regardless of scrolling activity

**Comment by lasedgman** [comment]
Does it stay open with the suggested contacts/actions in the header, or when you scroll it closes everything (see below)?

![search-bar](https://user-images.githubusercontent.com/8165750/30838830-4beb923a-a2b1-11e7-8504-233bdae3bf1d.gif)

A sticky header could be done, but may not ideal for certain device screen realestate (see below) - I'd suggest closing this and waiting for feedback on _Dash_. There might be a better workflow/process needed if the user is trying to do something with the suggested box opened - could also be on a different screen or dependant on what screen they are on.
![group](https://user-images.githubusercontent.com/8165750/30838658-3f068364-a2b0-11e7-9859-4196df116245.png)

**Comment by cristiansc** [comment]
happy for better workflow - the main point is to be able to instantly do a search from wherever a user is, without having to look for the search bar - at least in the desktop version anyway
