### ISSUE TITLE
New Activity 'type' catgeories

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#26]
Can we also please add the following activity types
"request" - this is for entities such as Discovery/Hope/FFM/IIWO etc to use as an initial activity marker for requests coming through
"enquiry" - for when people ring/contact/email the church with various questions (e.g questions on beliefs/stances, location, information about various public/media/ programs, etc

**Comment by danlewis** [comment]
Added activity types Request and Enquiry - Now live
