### ISSUE TITLE
Archived Teams still showing in team management tree

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#28]
e.g. Team 'Test' in Vic HQ

And is there a way to revive archived teams?

**Comment by danlewis** [comment]
This issue appears to be two issues.

1. Archived Teams still showing in team management tree - I assume your referring to the mentors team assigning page. If so, this no longer shows archived teams

2. And is there a way to revive archived teams? Yes. In Teams, filter by Archived teams. Edit an archived team and set its status back to active.

I've also made that when a team is set to archived, the mentor is reset to nil for that team.

**Comment by danlewis** [comment]
This is now live. Closing issue.
