### ISSUE TITLE
Error when creating new contact from HQ

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#29]
One of our users tried to create a new contact from their HQ (instead of Hub) and got an 'error' message. Is it possible to turn this error message into a notification telling them they need to create a contact within a team rather than from HQ?

**Comment by danlewis** [comment]
This seems like a duplicate of #36 which was fixed.

The contact can indeed be created in the HQ although a bug was preventing the page from loading correctly.
