### ISSUE TITLE
Colour Scheme

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#3]
Update colour scheme to closer resemble church brand and/or other church websites (e.g. search.adventistchurch.com)

**Comment by lasedgman** [comment]
Discuss this when _Dash_ has been launched (integrate with branding guidelines)

**Comment by lasedgman** [comment]
With the unknown official launch date of the Dash integration, let's work on a stop gap solution for bringing in the branding colours across Product site, Web app, Mobile app.

**Comment by cristiansc** [comment]
What are the barriers for the Dash integration?

**Comment by Kalvindever** [comment]
Dan/Brett, 
Given the time frames I would be hesitant about implementing Dash right now with limited time before the "launch".     From a branding perspective it would be better (at least in my view) have Orange.  At the very least in the box at the top left hand corner - the same colour everywhere might not work but it would be align more closely with the rest of the church branding.

**Comment by cristiansc** [comment]
If dash provides a significant/different UI/UX change, it may be better to have it prior to Feb than having to re-familiarise a growing number of users with the new version afterwards?

**Comment by Kalvindever** [comment]
Guys can comment – but I don’t want to increase risk at the moment.

Kalvin

**Comment by cristiansc** [comment]
How long does it take to implement? What are the potential risks?

**Comment by brettdonald** [comment]
UI/UX changes associated with Dash integration:
- Login process is handled fully within AdHub, there is no redirect to myAdventist and back. This will also bring the web app into line with the mobile app regarding which login methods are supported; so the supported methods will be Staff and Password, the unsupported methods will be Facebook, Google, Microsoft, Yahoo.
- More options are available for working with lists and tables
- The overall layout does NOT change in any significant way

Dan estimated a three weeks for Dash integration (that's the total time for three dashboards: team, org and console). The main risks are that:
- this could be an underestimate, and it could take longer
- some APIs may need to change, which will have flow-on effects to the mobile app, and the mobile app developer (that's me) is on leave from 13/12/17 to 26/1/18

Note that Dash does not bring any particular colours or branding to a web app. The app provides style information to Dash, not the other way around.

Let's just go back to the beginning for a minute. It seems that this ticket is simply about colour scheme. The GC identity guidelines don't specify any particular colour, although the revised SPD guidelines (which haven't been published yet) will presumably specify orange as the brand colour. So if this is simply a request to get rid of purple and use orange instead, let's just do that and leave Dash out of it.

**Comment by Kalvindever** [comment]
Thanks Brett – I think its just a colour change that the request is about.    Its about making it look like something that the church has done – therefore Orange is the main colour.

As you have described – the risk on the Dash side is beyond what I think we need to have for the moment.


Kalvin
