### ISSUE TITLE
Ability to delete/archive contacts from HQ

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#37]
A hq user has entered a contact twice (Shane Garth) and assigned it to two different hub users.
Can we have an option for HQ users to both delete/archive and move contacts or re-assign?

**Comment by danlewis** [comment]
I'm splitting this up into two seperate issues. The second issue been to re-assign contacts

**Comment by danlewis** [comment]
HQ users can now delete contacts by going to the contacts page > Settings > Delete.

This will be available in the next release.

**Comment by danlewis** [comment]
This is live
