### ISSUE TITLE
Contact in multiple teams/hq's

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#4]
Enable a contact to exist in more than on team/hub/hq - e.g. young person in individual bible study with local pastor plus small group at school - both pastor and chaplain to have shared access to contact who may exist in both the church and school team

**Comment by cristiansc** [comment]
Can we please have a 'share' contact option in addition to 'transfer'

This will allow multiple users to be able to care for the same contact where appropriate - e.g. school/church, pastor/member, etc

And the ability from their settings tab to see who else is sharing this contact and also ability of primary contact creator to delete other users from sharing contact. - this needs a bit more thought on how it could work

**Comment by lasedgman** [comment]
Similar to  https://github.com/adventistmedia/adventisthub-support/issues/96. Closing this issue.
