### ISSUE TITLE
Dashboard Mentor data not updating

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#44]
for NNSW, most teams have been assigned a mentor, however the dashboard still shows 84 teams without a mentor even after a re-fresh

**Comment by danlewis** [comment]
The dashboard "things to do" list is cached for one hour to improve performance - so it should already be updated. To help a little I've changed the cache expiry to 10 minutes for the next release

**Comment by danlewis** [comment]
Cache Expiry change now live
