### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/adventisthub-support#45]
Marketing will have two marketing methods – email and SMS.

**Email Marketing**

Before using this feature the HQ would need to connect to their own Mailchimp account.

Steps to send email:
Create a list of contacts who are subscribed to email marketing notifications and have an email address.
Click to automatically generate the campaign list in Mailchim and create an unsubscribe web hook and an email sent webhook.
Go to Mailchimp to create a new email using the campaign list.
Automatically create an activity for the contact about the email sent
If a contact unsubscribes from the email, the mailchimp webhook will automatically notify Adventist Hub to unsubscribe the contact from future email marketing messages.

**SMS Marketing**

Before using this feature the HQ would need to connect to their conferences Twilio account.

Steps to send SMS:
Create a list of contacts who are subscribed to SMS marketing notifications and have a mobile number.
Write and SMS message to send. An opt out messages is automatically appended to the message as required by the Australian SPAM ACT. e.g. “ Reply STOP to opt-out”
Automatically create an activity for the contact about the SMS sent.
If the user sends a reply SMS with the word “STOP” they will be automatically unsubscribed for the SMS marketing notifications.
If the user sends a reply the SMS will be stored for future reference.

**Creating a contact list**

To create a contact list the HQ needs to be able to filter contacts. The following filtering options could added:
Gender (male, female)
Age (greater or equal to X,  less than or equal to X)
Location: within radius from a point (latitude & longitude)
Activity (e.g. All who attended an event series, All who completed study X)
Status (active, unavailable)

**Comment by cristiansc** [comment]
This looks good Dan,
I'm wondering what are the pros and cons of making this available to team mangers too?

**Comment by danlewis** [comment]
Luke and I also had this conversation regarding giving these features to Hub. 

Conferences typically have a paid communication director and this would be the person who's using the marketing features in HQ - their trained and have marketing skills typically.

A church on the other hand has a pastor with typically no experience and therefore is more likely to send out less professional or "spam like" emails/sms which may have a negative effect on the image of the church.

There are people who are excepts to this, but it would think this covers the 90% of churches/conferences.

I can see benefits for Hubs/pastors been able to market to there church members however rather then contacts.

**Comment by cristiansc** [comment]
At present, only NNSW and GSC (sort of) have a full time coms director. VIC, WA and SQLD, have some one part time. I know most of the comms directors well, and they are struggling to keep up with the conference requests for internal comms. My concern is that if we don't give pastors access to this feature and they wait for the conferences comms person to do it for them, it literally won't happen - ever :)
