### ISSUE TITLE
Create daily AH email notifications

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#46]

**Comment by danlewis** [comment]
With the new email notifications from alerts in v2 it probably isn't necessary to sen a daily email. But a weekly team email sent to all team leaders and the team owner would make sense. 
Question:
What day/hour should the email be sent that will people most likely to read it.. Maybe wednesday afternoon -  not to close to the weekend when leaders are most busy

**Comment by cristiansc** [comment]
Great - weekly emails are good.

I would recommend Monday morning local time, 9am. This way you start the new week with reminders for upcoming tasks/visits/follow-up?
