### ISSUE TITLE
Email to accountability Partner

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#51]
When an accountability partner is selected by the team leader - can we auto-generate an email for the partner with information about what this means for the accountability partner? I'm happy to script this when you are ready to build it

**Comment by danlewis** [comment]
can you provide the script email here

**Comment by cristiansc** [comment]
Dear [partner first name]

I would like to ask if you would be willing to be my ministry support partner.

What does this involve? Providing prayer, encouragement and accountability as I work to engage, support and nurture those on the journey of faith.

There may be some weeks where, for whatever reason, I may not be able to follow-up with some of regular contacts. When this happens, you will get an email encouraging you to contact me and see how am I doing, and what, if any support I may need to care for those entrusted to me.

I would be grateful if you could keep me in prayer and contact me at [ user email live link] or SMS/ring me on [user mobile] to see how am I going and what support I may need to provide timely spiritual support for those in my care.

Thank you for being willing to support me in ministry and please do not hesitate to contact me if you have any questions.

Kind regards,

[User first name] [User last name]

**Comment by cristiansc** [comment]
Updated support partner weekly accountability email:

Dear [partner first name]

Thank you for your prayers and support of [user first name] [user last name] in ministry.

[user first name] has [# of overdue contacts] contacts that need to be followed-up.

Could you please contact [user first name] and see what, if any, support they may need?

[user first name] can be contacted at:

[user email]
[user mobile]

Thank you for supporting ministers of the Gospel

**Comment by danlewis** [comment]
A welcome email is now sent partner after create
