### ISSUE TITLE
Contact double up

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#53]
Is there a way for the system to auto-generate a notification to a contact's manager when a new contact has been entered anywhere in the system with potentially similar details?

e.g. discovery enters Paul Smith as a new contact - I am following up Paul Smith - system detects a second Paul Smith and verifies all fields (e.g. email, state, address, etc) and if it looks like it might be the same user, send a contact to pastor allowing them to verify and merge the two contacts

**Comment by brettdonald** [comment]
We'll work on merging contacts as a start

**Comment by cristiansc** [comment]
I think the duplicate finder in v. 2.0 is a good step forward as well - combined with the contact sharing suggestions at item #96 and this won't be an issue.
