### ISSUE TITLE
V2 - Church Membership Edition

### ISSUE THREAD

**Issue by danlewis** [adventistmedia/adventisthub-support#57]
This is a discussion a on v2 of the AdventistHub. This will primarily be about given teams the ability to properly add church members rather than only contacts. These changes will hopefully better setup the app for future member specific related features such as rostering and most importantly avoid a future rework of the upcoming mobile app. 

Suggest features

- [ ] Contact to be renamed Person. A person is a more generic term for either a contact or a member; at the end of the day we're all people.

- [x] Contact status to be changed to accomodate People. Current status's are {active, unavailable, baptized, do_not_contact, deleted}. New status's would be {contact, member, former member, deceased}. Whether a person is available or not is managed separately.

- [ ] Rename Hub to Team. This is not refererring to the overall product name but the team dashboard. Hub and team can be used interchangeable currently and the term team is much clearer. hub.adventistchurch.com would become team.adventistchurch.com. All references to Hub in the Hub dashboard would be updated to Team.

- [ ]  A Persons next visit is currently set as a date which can not be modified. This should be changed to a datetime and users should be able to update this as need be. This will help resolve issues with calendar events (currently all next visits are just set to 9am).

- [x] Memberships can have one of the following roles: {member, leader, manager}. Suggest to rename manager to owner. This helps to more clearly define the role or a leader vs a manager and is a commonly used term in other apps.

- [x] Set which people a user has access too. Currently a person belongs to a single user but leaders and managers can also view them. Instead a person should be accessible by any number of users. e.g. a church elder may need to view all church members assigned to them in a set region to follow up.

- [ ] People can have additional data recorded against them - their WWCC # (Working with Children Check), SPD Membership ID. Note that the current SPD membership system has no API to interact with at present unfortunately.

- [x] Login. The currently myAdventist login process is not ideal from the perspective of the UI, UX, branding and security. Create a list of suggestions for SPD to consider implementing.

- [x] The People view should only show people who belong to the team the user is currently in rather than all people assigned a user from all teams. This helps to complete separation of people between teams.

- [x] The concepts of Events and Recurring Events/Events series is still too complicated and confusing. This needs to be simplified further throughout the HQ and Team dashboards.

These feature list is currently open for discussion as expected to be completed within a 8 day timeframe followed by starting of the mobile app.

**Comment by cristiansc** [comment]
Hi Dan - thanks for all your work on this - great direction

1. Not sure if 'persons' as a tab works (or people). Contact is a commonly used term - person is not. 'Person' may create more confusion than it is trying to solve. A typical pastor/church may split the categories Into members and contacts (or possibly non-members - hence relating more to the status than the tab identifier). Even Apple's address book uses the term contact as a generic term to refer to people, without have the clumsiness of transition from singular to plural :) Happy to chat through further on the phone

2. Status sounds good

3. Team is good

4. Agreed on set visit date

5. owner is fine

6. User access - does this mean and/or include allowing a contact to be accessed by multiple users across varying teams/hq's?

7. extra data sounds good

8. Log-in urgent and I have asked SPD to address this repeatedly - at present, it does not log out users - major security flaw

9. Limited contact view per team - agreed - but need to have option to view all - a pastor doesn't always think in terms of teams when following up contacts

10. Agreed on events simplification - perhaps just a single event option, with the possibility of simply adding extra sessions to it

**Comment by danlewis** [comment]
V2 is now live. One key feature still not live is WWCC - this will be going live on Monday most likely
