### ISSUE TITLE
Addresses not auto-filling

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#6]
e.g. 10 Beasley Sreet, Moore, WA - exists in Google Maps, and search.adventistchurch but does not show/load in hub

**Comment by cristiansc** [comment]
Same for 95 Wheatley Street, Gosnells

**Comment by cristiansc** [comment]
21 Wanliss Street Rockingham another one

**Comment by cristiansc** [comment]
Just checked - once saved, it works and maps correctly - it seems to not work only when auto-filling text when entering a new address

**Comment by amnwebmaster** [comment]
For address autocomplete we use the service kleber (http://kleber.datatools.com.au/predictive-australian-address-capture/) who themselves use Australia Posts PAF (https://auspost.com.au/business-solutions/data-marketing-services/supporting-our-data-partners/address-data) which is described as "Australia Post's own mail delivery database, PAF contains details on every delivery point in Australia".

My guess would be that those churches don't have mail boxes and hence are not coming up in results.

As the the autocomplete is a not required to complete the address and more so "candy" users should be fine without it.
