### ISSUE TITLE
Importing decisions via bulk upload

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#62]
How can we create a process whereby decisions (or decision card data) can be entered via the bulk-upload process? useful for camps, events, etc?

**Comment by danlewis** [comment]
As this is a very common workflow, we could add a column "decision" to the spreadsheet. If text is added, a completed activity will automatically be added to the contact on create

**Comment by cristiansc** [comment]
If it is 'decision' with a free text field fill - could we make that import as a 'to do' for follow-up?
i.e. new activity created = enquiry
description text = text entry from 'decision' column on bulk upload

**Comment by danlewis** [comment]
Added and live
