### ISSUE TITLE
Team Management Tree Alphabetical Order

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#7]
When in the tree view for team management, the teams under each region are not listed alphabetically - can we please have this in alphabetical order?

**Comment by cristiansc** [comment]
I noticed when I did a team management edit using the tree view, and I saved the edit, it re-arranged the teams into some order (not sure what - maybe creation date) even though I had manually sorted alphabetically

**Comment by amnwebmaster** [comment]
Teams are now sorted a-z.

This will be in the next release later today
