### ISSUE TITLE
Live search

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#70]
Is it possible to have a live search feature which shows/hides results as you're typing - especially when searching for contacts or teams

**Comment by danlewis** [comment]
Live search is now available in Team contacts for Hub - this is because all contacts can fit on a single long page.
For HQ we wouldn't implement this as would mean a bit if work making all tables load via JS rather HTML. It would be nice but i don't see as a high demand feature to be added
