### ISSUE TITLE
Mentor Reports

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#72]
Information useful for mentors:

1. Church - # of contacts - # of active and on time vs # overdue for followup

2. Church - # contacts by 'approach'/'brand'/'campaign'

3. Church - # of members visited in last 12/24/36 months vs total # of members

4. Region - same parameters as 1-3

**Comment by danlewis** [comment]
Mentor Reports have been added. They are sent out every fortnight on a monday.

The data in the report is a little different  as its based around the idea of trends to help mentors see how teams have progressed. over time we can continue to add more data points to the report.
