### ISSUE TITLE
Ability for Team Members to transfer contacts

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#74]
There needs to be a way for a regular team member to transfer contacts internally, or at the very least send contacts back to 'owner' for re-distribution

really should be able to transfer internally within team - should need owner for every transfer

**Comment by danlewis** [comment]
This can already be done. Go to the contacts summary. On the about card you can see who the contact is assigned to and assign them to any one else in the team. This features is also available in Team Contacts.
A user could unassigned themselves. On the Team Dashboard Notices card the number of unassigned contacts would show up highlighting this.

**Comment by cristiansc** [comment]
I see - thanks :)
