### ISSUE TITLE
Notification + Email when assigning todo's to other users

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#75]
Can we generate a notification/email (with option to turn emails off from settings) when another user assigns me/others a todo? That way I know when another user wants me to do something related to a particular contact

**Comment by cristiansc** [comment]
And then, when the 'other' user completes the activity, notify the 'activity' creator in notifications and by email

**Comment by danlewis** [comment]
This should be in place. closing. please reopen if still an issue
