### ISSUE TITLE
Email notification for contact transfer even if user hasn't activated account yet

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#77]
Can we make sure email notifications for changes/transfers/todos etc are sent even if a user hasn't activated their account yet?

They have to have been added as a user to receive notifications - but ensure these are sent to their email even if they haven't yet activated their accounts

**Comment by danlewis** [comment]
Email alert notifications will by default be sent to all contacts who have either a pending or active account (unless they have unsubscribed from receiving such notifications)
