### ISSUE TITLE
Hide/archive deleted contacts !

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#80]
Is there a way to ‘hide’ / archive deleted contacts so they don’t keep showing in my ‘contacts’ list?

**Comment by danlewis** [comment]
i noticed that Archived team's were showing up in the Hub and Hq Team switch - this was fixed this afternoon. If this was not what your referring to, please reopen

**Comment by cristiansc** [comment]
I was referring to contacts - I am in Vostok - and in 'my contacts' can see a number of 'deleted' contacts

**Comment by danlewis** [comment]
During the v2 migration all contacts had assignments created - this should not have happened for delete contacts. This has now been fixed
