### ISSUE TITLE
Sorting not working for Contacts

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#84]
Tried to do the following
HQ - NNSW
click - contacts
click - status - no change

click 'users' tab
click - status - no change/sorting

**Comment by danlewis** [comment]
Contacts - All: status was reordering for me
Contacts  - Users: status was not sorting, this has been fixed. Also renamed status to Account here for clarity as this was referring to the account status and not the membership status

**Comment by cristiansc** [comment]
Working for me now too under 'users' - thanks
