### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#86]
evening/morning Dan - something broken :) - i'm in Vic  HQ  > Contacts tab > click on the '>' (next) arrow to go to page 2 - getting an 500 error page

Get the same when I try to do a search in the search field on the contacts page too

**Comment by danlewis** [comment]
I'm unable to replicate this bug in Vic HQ. Are you still seeing this?

**Comment by cristiansc** [comment]
Not showing up for me anymore.
