### ISSUE TITLE
Live Chat

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#88]
Dan - my wife gave me a great idea.

Can we please have a live chat/support functionality using some existing chat platform with a mobile app version?

There's a number of such apps out there - I've tried heaps, and am currently using Chatra for a personal project. That way, we can have live support for users - with messages sent straight to phone apps for whenever myself/you/local conference support are online - and to emails when offline.

what do you think?

**Comment by brettdonald** [comment]
Another possibility is [tawk.to](https://www.tawk.to). Just had a chat 😂 with them and the service is 100% free. They also have messaging fallback for when no agents are online. They have the following revenue streams: (a) you can opt to remove the "tawk.to" branding for $100 per annum, and (b) you can hire trained agents to answer chats on your behalf for $1 per hour.

**Comment by cristiansc** [comment]
I've tried tawk.to but didn't find it as good as Chatra - but happy to try it again :)

**Comment by brettdonald** [comment]
I have no experience with either. I see that the free Chatra account limits you to having only one agent online at a time. I imagine that in time we'd want at least one agent per conference, so we'd need a paid account which is $180 per (concurrently online) agent per annum.

**Comment by cristiansc** [comment]
Yep - most of the ones with better features/stability cost - Chatra is cheaper than some of the others out there :) I've tried about 6-7 different ones before settling on Chatra - there are some that offer more insights/data - but too complex for what we need and again, not as intuitive/user-friendly/cheap.

We can always start with tawk.to as it's free, and move to a different service if/when needed

Does it take much to setup tawk.to into AdHub?

**Comment by cristiansc** [comment]
17 mins after my above comment - I get an email from Tawk.to :)

There's nowhere to hide :)

**Comment by brettdonald** [comment]
Everyone wants to tawk.to you about it! If we go with Chatra, no worries, we'll just send the bill to your wife. We could even roll our own solution using [socket.io](https://socket.io), [Pusher](https://pusher.com) or [Faye](https://faye.jcoglan.com). Interesting to see what Dan thinks on Monday.

**Comment by danlewis** [comment]
This is to be implemented by Cristian on disciple.org.au. Links have been added to Adventist Hub directing them to the page
