### ISSUE TITLE
Ownership Transfer

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#89]
who/how can team ownership be transferred? only hq?

**Comment by danlewis** [comment]
Implemented for HQ and Hub

**Comment by cristiansc** [comment]
how do you change ownership?

**Comment by danlewis** [comment]
In a Hub, go to Team Dashboard > Members > Transfer Ownership
In a HQ, go to Teams > [select team] > Contacts > Transfer Ownership

**Comment by cristiansc** [comment]
Currently has Tony Sargent listed as team owner - must be a default sample? rather than actual owner?


Keep
Keep the current owner Tony Sargeant and demote their role to team member


Remove
Remove the current owner Tony Sargeant from the team
