### ISSUE TITLE
HQ Team Filter not working in CRM Console

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#9]
When filtering teams by 'HQ' in the CRM Console Teams tab, it displays a blank list

**Comment by cristiansc** [comment]
Seems to be working when I do a page refresh or by clicking on another tab and coming back to this one. it didn't work when I did just an 'update' after selecting 'HQ' for the filter

**Comment by amnwebmaster** [comment]
I'm having trouble replicating this bug. Can you please provide detailed steps to reproduce.

**Comment by cristiansc** [comment]
Hi Dan,
Not working for me either - I'll close it for now, and let you know if it happens again
