### ISSUE TITLE
Do we want team members (not owners/leaders) to be able to edit/modify contact assignments other than transfers?

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#94]
ie. at the present, they can delete assignments from the management pop-up. We want them to be able to re-assign, but not delete. only leaders/owners can delete

**Comment by danlewis** [comment]
Team members can now only delete their own assignment from a contact instead of all other assignments.
Team leaders and owners can delete all assignments.
Now live

**Comment by cristiansc** [comment]
good work :)
