### ISSUE TITLE
Activity view limitation

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#97]
When I click on a contact, then 'activities' and view the activity log, I have the following issue.

In v. 1.0 I could see something like:

"Request" as the main heading
And then decision points 1,2,3 etc. Which meant I didn't have to click on the 'edit' tool to see what the decision was.

In v.2 however I have to click on the 'edit' tool to see what the decision is. Can we please fix this so that the 'decision' or 'description' field box contents are visible on the main 'activity' log screen without having to click on the edit tool?

Can we also link the 'heading' (i.e. the 'activity type' visible on the activity log so when you click on it it takes you to the edit screen? Or at least a review screen?

(see link https://cdn.disciple.org.au/wp-content/uploads/2017/05/22160558/Decision-info.jpeg)

**Comment by danlewis** [comment]
Completed activities now show the description and feedback.
